export const subjectsData = [
  {
    id: 1,
    subject: "Mathematics",
    code: "MATH101",
    teacher: "Sarah Connor",
    hours: "5h",
    grade: "Grade 5",
  },
  {
    id: 2,
    subject: "Science",
    code: "SCI101",
    teacher: "Robert Chen",
    hours: "5h",
    grade: "Grade 3",
  },
  {
    id: 3,
    subject: "English",
    code: "ENG101",
    teacher: "Maria Santos",
    hours: "5h",
    grade: "Grade 7",
  },
  {
    id: 4,
    subject: "History",
    code: "HIS101",
    teacher: "James Porter",
    hours: "5h",
    grade: "Grade 4",
  },
  {
    id: 5,
    subject: "Arts",
    code: "ART101",
    teacher: "Lisa Park",
    hours: "5h",
    grade: "Grade 8",
  },
  {
    id: 6,
    subject: "Physical Education",
    code: "PE101",
    teacher: "David Kim",
    hours: "5h",
    grade: "Grade 6",
  },
];